.TH PWMAN3 1 "29 June 2013"
.SH NAME
pwman3 \- command line password manager
.SH SYNOPSIS

\fBpwman3\fP [\fIoptions\fP]

.SH DESCRIPTION

.TP
\fB\-c, \-\-config\fP FILE
Read the configuration from \fBFILE\fP instead of the default
\fB~/.pwman3/config\fP.

.TP
\fB\-e, \-\-encryption\fP ALGORITHM
Possible options are: AES(default), ARC2, ARC4, Blowfish, 
.br
CAST, DES, DES3, IDEA, RC5.

.TP
\fB\-d, \-\-database\fP FILE
When using the default sqlite backend, use \fBFILE\fP 
.br 
to read/store passwords.


.TP
\fB\-k, \-\-convert\fP 
Convert old DB format to Version >= 0.4. 
The databse that will be converted is the one found in the 
.br
config file, or the one given as command line argument.

.TP
\fB\-h, \-\-help\fP
Display help and exit.

.SH AUTHOR

This manpage has been written by Julien Louis <ptitlouis@sysif.net> 
.br
for the Debian GNU/Linux system but may be used by the others.
